services:
  web:
    image: nginx:latest
    container_name: compose-web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: compose-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: appdb
